import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Top } from "@/app/components/Layout"
import React from "react";

//const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressContentEditableWarning={true}>
    <head>
      <title>Han's Calendar</title>
      <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    </head>
    {/*<body className={inter.className}>*/}
        <body className="bg-gray-300">
          <Top >
              {children}
          </Top>
      </body>
    </html>
  )
}
